version: '3.9'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-docker:/var/lib/mysql
    ports:
    - "3306:3306"

  backend:
    depends_on:
      - db
    build: ./backend
    environment:
      PORT: 5000
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/src:/app/src
    command: [ "./wait-for-it.sh", "db:3306", "--", "npm", "start" ]

  front:
    depends_on:
      - backend
    build: ./frontend
    environment:
      BACKEND_URL: http://backend:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  mysql-docker:
