name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: 0.0.${{ github.run_number }}-${{ github.sha }}

jobs:
  build_backend:
    name: Build - Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: 208822006106.dkr.ecr.eu-west-2.amazonaws.com/real-estate-backend:${{ env.VERSION }}

  build_frontend:
    name: Build - Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: 208822006106.dkr.ecr.eu-west-2.amazonaws.com/real-estate-frontend:${{ env.VERSION }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build_backend
      - build_frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - uses: hashicorp/setup-terraform@v3
