name: PR pipeline
on: [push]
#on: [pull_request]

jobs:
  run-pr-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare file with secrets
        run: 'echo "$ENV_FILE" > .env'
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Debug - list files
        run: ls -la

      - name: Debug - log file content
        run: cat .env | base64

      - name: Run app
        run: docker-compose up -d

      - name: Wait
        run: sleep 30

      - name: Get containers status
        run: docker ps -a

      - name: Log container status
        run: docker-compose logs

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          working-directory: frontend
          record: true
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
