name: PR
on: [pull_request]

jobs:
  cypress-tests:
    name: Cypress E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare file with secrets
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: 'echo "$ENV_FILE" > .env'

      - name: Run app
        run: docker compose up -d

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          working-directory: frontend
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  frontend:
    name: Frontend checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Lint JS
        run: npx eslint

      - name: Create production build
        run: npm run build

  backend:
    name: Backend checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: backend/.nvmrc

      - name: Install Dependencies
        run: npm ci
